### PR TITLE
podman: cleanup and reorder

### PR DESCRIPTION
**Pull request by bamhm182**
### Description

Reviewing to help bring this in line with home-manager's contribution guide. I want to review this further before requesting my branch actually be merged, but wanting to talk about it as well.

- I removed any top level configs with the exception of those that either had some assumed defaults (like ContainerName) or would likely be lists or sets (like PublishedPorts, Volumes, etc.) so they can be better used and parsed.
- Moved a lot of the formatX functions into more generic formatListSpaces (Key=Val1 Val2), formatListNewlines (Key=Val1\nKey=Val2), etc. functions so that we didn't have a separate function for formatting each setting.
- Configured it so that extraXConfig attributes would override their top level attributes if both are defined, or use it if only extraXConfig's version is defined. For example, ..."mysleep".extraUnitConfig.Description = "testing" would override ..."mysleep".description = "Standard description".
- Alphabetized everything for easier discovery
-  Added extraXConfig options for each section in the quadlet unit files, so if things get added/removed/people want to modify them/etc, they should be able to be configured without us touching anything.
- Linted everything and tried to keep everything as standard as possible between files.
- Fixed issue with PodmanArgs always being present in the config, even when empty
- Probably a number of other things I'm forgetting.

### CODE REVIEW

**Comment by bamhm182** [comment]
@n-hass , I finally found the time to finish up the module rewrite as we'd talked about. I still need to thoroughly test everything to ensure it all works as I expect, but I believe it is ready for you to review.

Thanks for all the help! I think it wound up in a pretty great state, and it wouldn't have gotten there without us talking it over.

EDIT: I just realized that I didn't add back in the assertions. I still have a little work to do, but it shouldn't change much if you wanted to give it a review anyway.

**Comment by bamhm182** [comment]
Just realized that I didn't add back in the assertions. I still have a little more work to do, but it should be largely complete and I don't anticipate it changing much from its current state if you wouldn't mind having a look anyway.

**Comment by bamhm182** [comment]
From my testing, it should be good to go now. I was running into issues around home-manager not restarting modified user services, which caused issues when modifying them and running a nixos-rebuild. This was resolved with `systemd.user.startServices=true` and I think it's fine.

**Comment by n-hass** [comment]
Closing as #3 includes these changes

**Pull request closed without merging**
